package com.devcodespace.dcp.dao.entities;
// Generated Jul 7, 2015 6:07:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="datacrediticia"
    , uniqueConstraints = @UniqueConstraint(columnNames="identificacion") 
)
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String identificacion;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefonocasa;
     private String telefonocelular;
     private String correoelectronico;
     private Date fechanacimiento;
     private boolean habilitado;
     private Set historialcrediticios = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String identificacion, String nombres, String correoelectronico, Date fechanacimiento, boolean habilitado) {
        this.identificacion = identificacion;
        this.nombres = nombres;
        this.correoelectronico = correoelectronico;
        this.fechanacimiento = fechanacimiento;
        this.habilitado = habilitado;
    }
    public Cliente(String identificacion, String nombres, String apellidos, String direccion, String telefonocasa, String telefonocelular, String correoelectronico, Date fechanacimiento, boolean habilitado, Set historialcrediticios) {
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefonocasa = telefonocasa;
       this.telefonocelular = telefonocelular;
       this.correoelectronico = correoelectronico;
       this.fechanacimiento = fechanacimiento;
       this.habilitado = habilitado;
       this.historialcrediticios = historialcrediticios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcliente", unique=true, nullable=false)
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="identificacion", unique=true, nullable=false, length=13)
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="direccion", length=65535)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefonocasa", length=20)
    public String getTelefonocasa() {
        return this.telefonocasa;
    }
    
    public void setTelefonocasa(String telefonocasa) {
        this.telefonocasa = telefonocasa;
    }

    
    @Column(name="telefonocelular", length=20)
    public String getTelefonocelular() {
        return this.telefonocelular;
    }
    
    public void setTelefonocelular(String telefonocelular) {
        this.telefonocelular = telefonocelular;
    }

    
    @Column(name="correoelectronico", nullable=false, length=200)
    public String getCorreoelectronico() {
        return this.correoelectronico;
    }
    
    public void setCorreoelectronico(String correoelectronico) {
        this.correoelectronico = correoelectronico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechanacimiento", nullable=false, length=10)
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    
    @Column(name="habilitado", nullable=false)
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getHistorialcrediticios() {
        return this.historialcrediticios;
    }
    
    public void setHistorialcrediticios(Set historialcrediticios) {
        this.historialcrediticios = historialcrediticios;
    }




}


