package com.devcodespace.dcp.dao.entities;
// Generated Jul 7, 2015 6:07:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="datacrediticia"
    , uniqueConstraints = @UniqueConstraint(columnNames="rnc") 
)
public class Empresa  implements java.io.Serializable {


     private Integer idempresa;
     private String rnc;
     private String nombre;
     private String tipo;
     private boolean habilitado;
     private Set historialcrediticios = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String rnc, String nombre, String tipo, boolean habilitado) {
        this.rnc = rnc;
        this.nombre = nombre;
        this.tipo = tipo;
        this.habilitado = habilitado;
    }
    public Empresa(String rnc, String nombre, String tipo, boolean habilitado, Set historialcrediticios) {
       this.rnc = rnc;
       this.nombre = nombre;
       this.tipo = tipo;
       this.habilitado = habilitado;
       this.historialcrediticios = historialcrediticios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idempresa", unique=true, nullable=false)
    public Integer getIdempresa() {
        return this.idempresa;
    }
    
    public void setIdempresa(Integer idempresa) {
        this.idempresa = idempresa;
    }

    
    @Column(name="rnc", unique=true, nullable=false, length=9)
    public String getRnc() {
        return this.rnc;
    }
    
    public void setRnc(String rnc) {
        this.rnc = rnc;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="tipo", nullable=false, length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="habilitado", nullable=false)
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getHistorialcrediticios() {
        return this.historialcrediticios;
    }
    
    public void setHistorialcrediticios(Set historialcrediticios) {
        this.historialcrediticios = historialcrediticios;
    }




}


