package com.devcodespace.dcp.dao.entities;
// Generated Jul 7, 2015 6:07:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historialcrediticio generated by hbm2java
 */
@Entity
@Table(name="historialcrediticio"
    ,catalog="datacrediticia"
)
public class Historialcrediticio  implements java.io.Serializable {


     private Integer idhistorialcrediticio;
     private Cliente cliente;
     private Empresa empresa;
     private Moneda moneda;
     private Tipoproducto tipoproducto;
     private BigDecimal limitecredito;
     private Integer nocuota;
     private BigDecimal montocuota;
     private BigDecimal balanceactual;
     private Date fechatransaccion;
     private boolean habilitado;

    public Historialcrediticio() {
    }

	
    public Historialcrediticio(Cliente cliente, Empresa empresa, Moneda moneda, Tipoproducto tipoproducto, BigDecimal limitecredito, Date fechatransaccion, boolean habilitado) {
        this.cliente = cliente;
        this.empresa = empresa;
        this.moneda = moneda;
        this.tipoproducto = tipoproducto;
        this.limitecredito = limitecredito;
        this.fechatransaccion = fechatransaccion;
        this.habilitado = habilitado;
    }
    public Historialcrediticio(Cliente cliente, Empresa empresa, Moneda moneda, Tipoproducto tipoproducto, BigDecimal limitecredito, Integer nocuota, BigDecimal montocuota, BigDecimal balanceactual, Date fechatransaccion, boolean habilitado) {
       this.cliente = cliente;
       this.empresa = empresa;
       this.moneda = moneda;
       this.tipoproducto = tipoproducto;
       this.limitecredito = limitecredito;
       this.nocuota = nocuota;
       this.montocuota = montocuota;
       this.balanceactual = balanceactual;
       this.fechatransaccion = fechatransaccion;
       this.habilitado = habilitado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idhistorialcrediticio", unique=true, nullable=false)
    public Integer getIdhistorialcrediticio() {
        return this.idhistorialcrediticio;
    }
    
    public void setIdhistorialcrediticio(Integer idhistorialcrediticio) {
        this.idhistorialcrediticio = idhistorialcrediticio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idempresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmoneda", nullable=false)
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtipoproducto", nullable=false)
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }

    
    @Column(name="limitecredito", nullable=false, precision=20)
    public BigDecimal getLimitecredito() {
        return this.limitecredito;
    }
    
    public void setLimitecredito(BigDecimal limitecredito) {
        this.limitecredito = limitecredito;
    }

    
    @Column(name="nocuota")
    public Integer getNocuota() {
        return this.nocuota;
    }
    
    public void setNocuota(Integer nocuota) {
        this.nocuota = nocuota;
    }

    
    @Column(name="montocuota", precision=12)
    public BigDecimal getMontocuota() {
        return this.montocuota;
    }
    
    public void setMontocuota(BigDecimal montocuota) {
        this.montocuota = montocuota;
    }

    
    @Column(name="balanceactual", precision=20)
    public BigDecimal getBalanceactual() {
        return this.balanceactual;
    }
    
    public void setBalanceactual(BigDecimal balanceactual) {
        this.balanceactual = balanceactual;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechatransaccion", nullable=false, length=19)
    public Date getFechatransaccion() {
        return this.fechatransaccion;
    }
    
    public void setFechatransaccion(Date fechatransaccion) {
        this.fechatransaccion = fechatransaccion;
    }

    
    @Column(name="habilitado", nullable=false)
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


