package com.devcodespace.dcp.dao.entities;
// Generated Jul 7, 2015 6:07:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Indiceinflacion generated by hbm2java
 */
@Entity
@Table(name="indiceinflacion"
    ,catalog="datacrediticia"
    , uniqueConstraints = @UniqueConstraint(columnNames="periodo") 
)
public class Indiceinflacion  implements java.io.Serializable {


     private Integer idindiceinflacion;
     private String periodo;
     private BigDecimal indiceinflacion;
     private boolean habilitado;

    public Indiceinflacion() {
    }

    public Indiceinflacion(String periodo, BigDecimal indiceinflacion, boolean habilitado) {
       this.periodo = periodo;
       this.indiceinflacion = indiceinflacion;
       this.habilitado = habilitado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idindiceinflacion", unique=true, nullable=false)
    public Integer getIdindiceinflacion() {
        return this.idindiceinflacion;
    }
    
    public void setIdindiceinflacion(Integer idindiceinflacion) {
        this.idindiceinflacion = idindiceinflacion;
    }

    
    @Column(name="periodo", unique=true, nullable=false, length=6)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    
    @Column(name="indiceinflacion", nullable=false, precision=5)
    public BigDecimal getIndiceinflacion() {
        return this.indiceinflacion;
    }
    
    public void setIndiceinflacion(BigDecimal indiceinflacion) {
        this.indiceinflacion = indiceinflacion;
    }

    
    @Column(name="habilitado", nullable=false)
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


