package com.devcodespace.dcp.dao.entities;
// Generated Jul 7, 2015 6:07:19 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name="moneda"
    ,catalog="datacrediticia"
    , uniqueConstraints = @UniqueConstraint(columnNames="codigo") 
)
public class Moneda  implements java.io.Serializable {


     private Integer idmoneda;
     private String codigo;
     private String descripcion;
     private BigDecimal tasacompra;
     private BigDecimal tasaventa;
     private boolean habilitado;
     private Set historialcrediticios = new HashSet(0);

    public Moneda() {
    }

	
    public Moneda(String codigo, String descripcion, BigDecimal tasacompra, BigDecimal tasaventa, boolean habilitado) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.tasacompra = tasacompra;
        this.tasaventa = tasaventa;
        this.habilitado = habilitado;
    }
    public Moneda(String codigo, String descripcion, BigDecimal tasacompra, BigDecimal tasaventa, boolean habilitado, Set historialcrediticios) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.tasacompra = tasacompra;
       this.tasaventa = tasaventa;
       this.habilitado = habilitado;
       this.historialcrediticios = historialcrediticios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmoneda", unique=true, nullable=false)
    public Integer getIdmoneda() {
        return this.idmoneda;
    }
    
    public void setIdmoneda(Integer idmoneda) {
        this.idmoneda = idmoneda;
    }

    
    @Column(name="codigo", unique=true, nullable=false, length=3)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="descripcion", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="tasacompra", nullable=false, precision=5)
    public BigDecimal getTasacompra() {
        return this.tasacompra;
    }
    
    public void setTasacompra(BigDecimal tasacompra) {
        this.tasacompra = tasacompra;
    }

    
    @Column(name="tasaventa", nullable=false, precision=5)
    public BigDecimal getTasaventa() {
        return this.tasaventa;
    }
    
    public void setTasaventa(BigDecimal tasaventa) {
        this.tasaventa = tasaventa;
    }

    
    @Column(name="habilitado", nullable=false)
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="moneda")
    public Set getHistorialcrediticios() {
        return this.historialcrediticios;
    }
    
    public void setHistorialcrediticios(Set historialcrediticios) {
        this.historialcrediticios = historialcrediticios;
    }




}


